// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SmartDataHub.Models;
using System;

namespace SmartDataHub.Migrations
{
    [DbContext(typeof(SmartDataHubStorageContext))]
    partial class SmartDataHubStorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartDataHub.Models.CycleMachineConfiguration", b =>
                {
                    b.Property<int>("CycleMachineConfigurationId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("CycleInputPin");

                    b.Property<int>("MachineId");

                    b.Property<string>("MachineName")
                        .IsRequired();

                    b.Property<int>("MachineStateTimeOut");

                    b.Property<int>("PublishingIntervall");

                    b.Property<int>("SmartAgentId");

                    b.HasKey("CycleMachineConfigurationId");

                    b.HasIndex("SmartAgentId");

                    b.ToTable("CycleMachineConfiguration");
                });

            modelBuilder.Entity("SmartDataHub.Models.InputMonitoringConfiguration", b =>
                {
                    b.Property<int>("InputMonitoringConfigurationId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("InputPin");

                    b.Property<string>("MonitoringName")
                        .IsRequired();

                    b.Property<int>("OutputPin");

                    b.Property<int>("SmartAgentId");

                    b.HasKey("InputMonitoringConfigurationId");

                    b.HasIndex("SmartAgentId");

                    b.ToTable("InputMonitoringConfiguration");
                });

            modelBuilder.Entity("SmartDataHub.Models.SmartAgent", b =>
                {
                    b.Property<int>("SmartAgentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IpAddress")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("SmartAgentId");

                    b.ToTable("SmartAgent");
                });

            modelBuilder.Entity("SmartDataHub.Models.CycleMachineConfiguration", b =>
                {
                    b.HasOne("SmartDataHub.Models.SmartAgent", "SmartAgent")
                        .WithMany()
                        .HasForeignKey("SmartAgentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SmartDataHub.Models.InputMonitoringConfiguration", b =>
                {
                    b.HasOne("SmartDataHub.Models.SmartAgent", "SmartAgent")
                        .WithMany()
                        .HasForeignKey("SmartAgentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
